version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    networks:
      - fastify
    environment:
      - node.name=elastic_hihi-node
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    restart: always
    ports:
      - "9211:9200"
    volumes:
      - dataelasticseach:/usr/share/elasticsearch/data
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: master
      
    ports:
      - 27018:27017
    networks:
      - fastify
    volumes:
      - datamongo:/data/db
  postgres:
    image: postgres:13
    container_name: postgres
    networks:
      - fastify
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5421:5432"
    volumes:
      - "datapostgres:/var/lib/postgresql/data/pgdata"
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
  redis:
    image: redis:6
    container_name: redis
    networks:
      - fastify
    ports:
      - "6378:6379"
    command: redis-server --appendonly yes
    volumes:
      - "dataredis:/data"
networks:
  fastify:
    driver: bridge
volumes:
  dataelasticseach: {}
  datapostgres: {}
  dataredis: {}
  datamongo: {}
